// src/pages/confetti.page.svelte
<script lang="ts">
  // eslint-disable-next-line no-undef
  const onClick = () => window['confetti']();
</script>

<h1>Confetti</h1>

<svelte:head>
  <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js"></script>
</svelte:head>

<a href="/">go back</a>

<!-- svelte-ignore missing-declaration -->
<button on:click={onClick}> Fire confetti </button>

// src/pages/confetti.page.tsx
import { type Component, createEffect, onCleanup, onMount } from 'solid-js';

export const Page: Component = () => {

  onMount(() => createEffect(() => {
    console.log('add script');
    if (!window['confetti']) {
      const script = document.createElement('script');
      script.id = 'confetti';
      script.src = 'https://cdn.jsdelivr.net/npm/canvas-confetti@1.6.0/dist/confetti.browser.min.js';
      document.head.appendChild(script);
    }
  }));

  onCleanup(() => {
    // window['confetti'] will remain in memory
    const script = document.getElementById('confetti');
    if (script) {
      script.remove();
    }
  });


  const onClick = () => {
    if (window['confetti']) {
      window['confetti']();
    }
  };

  return (
    <>
      <h1>Confetti</h1>
      <button onClick={(e) => onClick()}> Fire confetti </button>
      <a href="/">go back</a>
    </>
  );
};
